### PR TITLE
Add latbin programs and deps. to allow producing confidence scores

### PR DESCRIPTION
**Pull request by riebling**
Hey, I think I've gotten this git process right, but 'sorry for the inconvenience' if not. Adding a few binaries from Kaldi to the eesen src/ tree to give us latbin/{lattice-best-path,lattice-prune,lattice-add-penalty,lattice-to-ctm-conf} in order to produce confidence scores, according to this email:

> you can simply leave out the lattice-align-words (which cannot be implemented in Eesen) line, and use lattice-to-ctm-conf from Kaldi. 
> 
> > On Tue, Mar 8, 2016 at 2:58 PM, Eric Riebling er1k@cs.cmu.edu wrote:
> > 
> >    There's been a request by a customer, and by Florian, to add confidence
> >    scores to EESEN decoding. I thought I could make it work by bringing in
> >    code to run get_ctm.sh in a different way, more like get_ctm_conf.sh in
> >    a different Kaldi experiment:

```
     $cmd ACWT=$min_acwt:$max_acwt $dir/scoring/log/get_ctm.ACWT.log \
      mkdir -p $dir/score_ACWT/ '&&' \
      lattice-prune --inv-acoustic-scale=ACWT --beam=5 "ark:gunzip -c $dir/lat.*.gz|" ark:- \| \
      lattice-align-words $lang_or_graph/phones/word_boundary.int ../final.mdl ark:- ark:- \| \
      lattice-to-ctm-conf --decode-mbr=true --inv-acoustic-scale=ACWT ark:- - \| \
      utils/int2sym.pl -f 5 $symtab \| \
      $filter_cmd '>' $dir/score_ACWT/$name.ctm || exit 1;
```

### CODE REVIEW

**Comment by yajiemiao** [comment]
Thanks for your contribution. Can you verify these functions/utilities in the context of Eesen? If they work, pls let me know and  I will merge your changes. If not, we want to keep the toolkit uncluttered.

**Comment by riebling** [comment]
These were the minimum amount of programs needed to implement
the confidence scoring by adding  lattice-prune, lattice-to-ctm-conf.
I might be able to get it even smaller if we don't need lattice-align-words.

Also I think in eesen, these programs may have been moved or belong in
the decoderbin/ folder.

Let me see how much success I have in producing confidence scores first,
and decide with Florian whether we want this to be part of Eesen by default,
at the expense of bringing in more of Kaldi.

I agree it's nice to keep it as uncluttered as possible.

On 03/17/2016 02:34 PM, Yajie Miao wrote:

> Thanks for your contribution. Can you verify these functions/utilities in the context of Eesen? If they work, pls let me know and I will merge your changes. If not, we want to keep the toolkit uncluttered.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub https://github.com/srvk/eesen/pull/44#issuecomment-198023660

## 

Eric Riebling      Interactive Systems Lab
er1k@cs.cmu.edu    407 South Craig St.

**Comment by yajiemiao** [comment]
why do you check in the hmm and tree folders, which I've been leaving out since the origin of Eesen?
In any case, lattice-align-words (and all the dependency) should NOT be added, because it simply does not work with Eesen.

**Comment by riebling** [comment]
I agree, now that I understand. I only checked those in when they were dependencies
needed in order to compile lattice-\* programs. I now understand that even fewer (I had
already reduced the number greatly) latbin/ programs are really needed.

Also in trying to produce confidence scores, I'm wondering if I'm doing something
wrong, piping the output of lattice-to-ctm-conf into int2sym.pl - but let me
worry about that separately from this email. :)

On 03/17/2016 02:58 PM, Yajie Miao wrote:

> why do you check in the hmm and tree folders, which I've been leaving out since the origin of Eesen?
> In any case, lattice-align-words (and all the dependency) should NOT be added, because it simply does not work with Eesen.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub https://github.com/srvk/eesen/pull/44#issuecomment-198034256

## 

Eric Riebling      Interactive Systems Lab
er1k@cs.cmu.edu    407 South Craig St.

**Pull request closed without merging**
